name: DEPLOY - PROD
on:
  workflow_dispatch:
jobs:
  terraform:
    name: deploy
    uses: GabrielSoares-Dev/workflows/.github/workflows/terraform-deploy.yml@master
    with:
      work_dir: ./
      environment: prod
      env_vars_path: env/prod.tfvars
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID_PROD}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_PROD}}