name: DEPLOY - STG
on:
  workflow_dispatch:
jobs:
  terraform:
    name: deploy
    uses: GabrielSoares-Dev/workflows/.github/workflows/terraform-deploy.yml@master
    with:
      work_dir: ./
      environment: stg
      env_vars_path: env/stg.tfvars
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID_STG}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_STG}}